version: '3.7'
services:

  helmfile:
    image: abdennour/helmfile:v0.138.7-aws-1.19.26
    working_dir: /wd
    volumes:
      - ${HOME}/.kube:/root/.kube
      - ${HOME}/.config/helm:/root/.config/helm
      - ${PWD}:/wd:ro
    environment:
      - KUBECONFIG=/root/.kube/config
      - DOMAIN=${DOMAIN}
      - CLUSTER_NAME=${CLUSTER_NAME}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - AWS_ACM_ARN=${AWS_ACM_ARN}
      - AWS_ECR_REPO=${AWS_ECR_REPO}
      - DOCKER_CONFIG_JSON=${DOCKER_CONFIG_JSON}
    network_mode: host
    command: apply
