{{- if .Values.imagePullSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .Values.imagePullSecret.value | b64enc }}
{{- end }}
