apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy_demo.fullname" . }}-postgres
  namespace: {{ .Values.namespaces.database }}
  labels:
    {{- include "deploy_demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
      name: postgres-port
  selector:
    app: {{ include "deploy_demo.fullname" . }}-postgres
