{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deploy_demo.serviceAccountName" . }}
  namespace: {{ .Values.namespaces.phoenix }}
  labels:
    {{- include "deploy_demo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deploy_demo.serviceAccountName" . }}-postgres
  namespace: {{ .Values.namespaces.database }}
  labels:
    {{- include "deploy_demo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
