apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy_demo.fullname" . }}
  namespace: {{ .Values.namespaces.phoenix }}
  labels:
    {{- include "deploy_demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodeport }}
      {{- end }}
  selector:
    app: {{ include "deploy_demo.fullname" . }}
