- name: Apt install dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    - docker-compose

- name: Assure that docker is active
  service:
    name: docker
    state: started
    enabled: yes

- name: Make user the owner of docker socket
  become: true
  file:
    path: /var/run/docker.sock
    owner: "{{ ansible_user_id }}"
    group: docker
